### ISSUE TITLE
Evaluate npm modules for removal

### ISSUE THREAD

**Issue by jlyon** [proudcity/proudcity-patternlibrary-boilerplate#1]
- [ ] "connect-modrewrite": "~0.7.9",
- [x] "grunt-angular-templates": "^0.5.7",
- [x] "grunt-contrib-clean": "~0.6.0",
- [ ] "grunt-contrib-connect": "~0.8.0",
- [x] "grunt-contrib-copy": "~0.6.0",
- [x] "grunt-usemin": "~2.4.0",
- [x] "grunt-wiredep": "~1.9.0",
- [x] "node-sass": "~0.9.6"

**Comment by aschmoe** [comment]
removed
